FROM node:20-slim

WORKDIR /app

COPY ./web/package.json /app/package.json
COPY ./web/package-lock.json /app/package-lock.json
RUN npm install

COPY ./web /app
EXPOSE 3000
RUN npm run build
CMD ["npm", "start"]